name: req_res_api
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  kartal: ^3.4.3
  flutter_riverpod: ^2.4.2
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  dio: ^5.3.3

  # UI Elements
  cached_network_image: ^3.3.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/lotties/

flutter_gen:
  output: lib/products/generation/
  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml